import {
  Patient,
  PatientCase,
  CaseNote,
  CaseEvent,
  CaseFollowup,
  Attachment,
  Notification,
  AuditLog,
  User,
} from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-sarah-chen',
    roleId: 'role-doctor',
    roleName: 'Doctor',
    fullName: 'Dr. Sarah Chen, MD',
    email: 'dr.sarah@medora.health',
    department: 'Cardiology',
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'usr-marcus-thorne',
    roleId: 'role-doctor',
    roleName: 'Doctor',
    fullName: 'Dr. Marcus Thorne, MD',
    email: 'dr.marcus@medora.health',
    department: 'Neurology',
    isActive: true,
    createdAt: '2026-01-02T08:00:00Z',
    updatedAt: '2026-01-02T08:00:00Z',
  },
  {
    id: 'usr-james-rodriguez',
    roleId: 'role-nurse',
    roleName: 'Nurse',
    fullName: 'James Rodriguez, RN',
    email: 'nurse.james@medora.health',
    department: 'Inpatient Care',
    isActive: true,
    createdAt: '2026-01-03T08:00:00Z',
    updatedAt: '2026-01-03T08:00:00Z',
  },
  {
    id: 'usr-elena-rostova',
    roleId: 'role-admin',
    roleName: 'Administrator',
    fullName: 'Elena Rostova',
    email: 'admin.elena@medora.health',
    department: 'Administration',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr-alex-kim',
    roleId: 'role-student',
    roleName: 'Student',
    fullName: 'Alex Kim',
    email: 'student.alex@medora.health',
    department: 'Medical Education',
    isActive: true,
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-01-05T08:00:00Z',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    patientIdentifier: 'MED-PT-2026-0001',
    firstName: 'Arthur',
    lastName: 'Pendelton',
    dateOfBirth: '1959-04-12',
    sex: 'Male',
    bloodType: 'O+',
    allergies: ['Penicillin', 'Sulfa drugs'],
    contactInformation: {
      phone: '+1 (555) 234-5678',
      email: 'a.pendelton@example.com',
      address: '742 Evergreen Terrace, Springfield',
      emergencyContact: {
        name: 'Martha Pendelton',
        relationship: 'Spouse',
        phone: '+1 (555) 234-5679',
      },
    },
    createdAt: '2026-01-10T09:15:00Z',
    updatedAt: '2026-01-10T09:15:00Z',
    archivedAt: null,
  },
  {
    id: 'pat-002',
    patientIdentifier: 'MED-PT-2026-0002',
    firstName: 'Eleanor',
    lastName: 'Vance',
    dateOfBirth: '1981-08-23',
    sex: 'Female',
    bloodType: 'A+',
    allergies: ['Aspirin', 'Ibuprofen'],
    contactInformation: {
      phone: '+1 (555) 345-6789',
      email: 'eleanor.vance@example.com',
      address: '12 Hilltop Manor, Boston, MA',
      emergencyContact: {
        name: 'Theodora Vance',
        relationship: 'Sister',
        phone: '+1 (555) 345-6780',
      },
    },
    createdAt: '2026-01-12T11:30:00Z',
    updatedAt: '2026-01-12T11:30:00Z',
    archivedAt: null,
  },
  {
    id: 'pat-003',
    patientIdentifier: 'MED-PT-2026-0003',
    firstName: 'Carlos',
    lastName: 'Morales',
    dateOfBirth: '1968-11-05',
    sex: 'Male',
    bloodType: 'B+',
    allergies: ['None known'],
    contactInformation: {
      phone: '+1 (555) 456-7890',
      email: 'cmorales@example.com',
      address: '405 Valencia Blvd, San Antonio, TX',
      emergencyContact: {
        name: 'Isabella Morales',
        relationship: 'Daughter',
        phone: '+1 (555) 456-7891',
      },
    },
    createdAt: '2026-01-14T14:20:00Z',
    updatedAt: '2026-01-14T14:20:00Z',
    archivedAt: null,
  },
  {
    id: 'pat-004',
    patientIdentifier: 'MED-PT-2026-0004',
    firstName: 'Aaliyah',
    lastName: 'Mansoor',
    dateOfBirth: '1994-02-18',
    sex: 'Female',
    bloodType: 'O-',
    allergies: ['Latex'],
    contactInformation: {
      phone: '+1 (555) 567-8901',
      email: 'amansoor@example.com',
      address: '88 Cypress Creek Rd, Austin, TX',
      emergencyContact: {
        name: 'Tariq Mansoor',
        relationship: 'Father',
        phone: '+1 (555) 567-8902',
      },
    },
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-01-18T10:00:00Z',
    archivedAt: null,
  },
  {
    id: 'pat-005',
    patientIdentifier: 'MED-PT-2026-0005',
    firstName: 'Robert',
    lastName: 'MacIntyre',
    dateOfBirth: '1954-06-30',
    sex: 'Male',
    bloodType: 'AB+',
    allergies: ['Contrast Dye', 'Morphine'],
    contactInformation: {
      phone: '+1 (555) 678-9012',
      email: 'robert.mac@example.com',
      address: '302 Highland Ave, Seattle, WA',
      emergencyContact: {
        name: 'Fiona MacIntyre',
        relationship: 'Spouse',
        phone: '+1 (555) 678-9013',
      },
    },
    createdAt: '2026-01-20T16:45:00Z',
    updatedAt: '2026-01-20T16:45:00Z',
    archivedAt: null,
  },
  {
    id: 'pat-006',
    patientIdentifier: 'MED-PT-2026-0006',
    firstName: 'Maya',
    lastName: 'Patel',
    dateOfBirth: '1998-09-14',
    sex: 'Female',
    bloodType: 'A-',
    allergies: ['None known'],
    contactInformation: {
      phone: '+1 (555) 789-0123',
      email: 'maya.patel@example.com',
      address: '55 University Ave, Chicago, IL',
      emergencyContact: {
        name: 'Raj Patel',
        relationship: 'Brother',
        phone: '+1 (555) 789-0124',
      },
    },
    createdAt: '2026-01-22T08:30:00Z',
    updatedAt: '2026-01-22T08:30:00Z',
    archivedAt: null,
  },
  {
    id: 'pat-007',
    patientIdentifier: 'MED-PT-2026-0007',
    firstName: 'Harold',
    lastName: 'Zimmer',
    dateOfBirth: '1945-12-01',
    sex: 'Male',
    bloodType: 'B-',
    allergies: ['Ciprofloxacin'],
    contactInformation: {
      phone: '+1 (555) 890-1234',
      email: 'hzimmer@example.com',
      address: '14 Oakridge Court, Denver, CO',
      emergencyContact: {
        name: 'Clara Zimmer',
        relationship: 'Daughter',
        phone: '+1 (555) 890-1235',
      },
    },
    createdAt: '2026-01-24T13:10:00Z',
    updatedAt: '2026-01-24T13:10:00Z',
    archivedAt: null,
  },
  {
    id: 'pat-008',
    patientIdentifier: 'MED-PT-2026-0008',
    firstName: 'Fatima',
    lastName: 'Zahra',
    dateOfBirth: '1973-03-25',
    sex: 'Female',
    bloodType: 'O+',
    allergies: ['Codeine'],
    contactInformation: {
      phone: '+1 (555) 901-2345',
      email: 'fzahra@example.com',
      address: '220 Garden Grove St, Phoenix, AZ',
      emergencyContact: {
        name: 'Youssef Zahra',
        relationship: 'Son',
        phone: '+1 (555) 901-2346',
      },
    },
    createdAt: '2026-01-26T15:50:00Z',
    updatedAt: '2026-01-26T15:50:00Z',
    archivedAt: null,
  },
];

export const INITIAL_CASES: PatientCase[] = [
  {
    id: 'case-001',
    patientId: 'pat-001',
    caseNumber: 'CASE-2026-0001',
    title: 'Acute Coronary Syndrome / Post-PCI Stent Surveillance',
    consultationReason: 'Chest heaviness radiating to left shoulder with shortness of breath on exertion.',
    status: 'Active',
    priority: 'Urgent',
    department: 'Cardiology',
    responsibleUserId: 'usr-sarah-chen',
    clinicalDocumentation: {
      chiefComplaint: 'Substernal chest tightness for 3 hours, associated with diaphoresis and mild nausea.',
      historyOfPresentIllness: 'Patient experienced sudden onset retrosternal crushing pain while walking up stairs. Rest provided partial relief after 20 minutes.',
      medicalHistory: 'Hypertension (10 yrs), Hyperlipidemia, Coronary Artery Disease. Non-smoker.',
      familySocialHistory: 'Father had myocardial infarction at age 62. Retired civil engineer.',
      examinationFindings: 'BP 148/92 mmHg, HR 88 bpm regular, SpO2 97% on room air. S1 S2 normal, no murmurs. Lungs clear to auscultation bilaterally.',
      investigations: '12-lead ECG: ST-segment elevations in leads II, III, aVF. High-sensitivity Troponin I: 480 ng/L (elevated). Echocardiogram: Mild inferior wall hypokinesis, EF 52%.',
      assessmentAndPlan: 'Acute Inferior STEMI status post emergent drug-eluting stent (DES) to RCA. Continue dual antiplatelet therapy (Aspirin + Ticagrelor), High-intensity Atorvastatin, Metoprolol. Monitor cardiac telemetry and renal panel.',
      medications: 'Aspirin 81mg daily, Ticagrelor 90mg BID, Atorvastatin 80mg QHS, Metoprolol Succinate 50mg daily.',
    },
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: '2026-02-03T14:15:00Z',
    closedAt: null,
  },
  {
    id: 'case-002',
    patientId: 'pat-003',
    caseNumber: 'CASE-2026-0002',
    title: 'Uncontrolled Type 2 Diabetes with Neuropathic Plantar Ulcer',
    consultationReason: 'Non-healing right plantar ulcer and worsening numbness in bilateral lower extremities.',
    status: 'Follow-up Required',
    priority: 'High',
    department: 'General Medicine',
    responsibleUserId: 'usr-sarah-chen',
    clinicalDocumentation: {
      chiefComplaint: 'Right first metatarsal head plantar ulcer present for 3 weeks without healing.',
      historyOfPresentIllness: 'Carlos reports progressive peripheral stocking distribution numbness. Noticed footwear abrasion 3 weeks ago which opened into a shallow wound.',
      medicalHistory: 'Type 2 Diabetes Mellitus x 12 years (poorly controlled), Diabetic Retinopathy.',
      familySocialHistory: 'Mother had T2DM and diabetic nephropathy.',
      examinationFindings: 'Right plantar 1.5 cm x 1.2 cm shallow ulcer, granulating base, minimal erythema at borders, no purulent drainage. Diminished monofilament sensation bilaterally.',
      investigations: 'HbA1c: 9.8%, Fasting Blood Glucose: 215 mg/dL, Plain Radiograph Right Foot: No osteomyelitis or cortical destruction.',
      assessmentAndPlan: 'Diabetic foot ulcer (Wagner Grade 1) with peripheral sensory neuropathy. Glycemic optimization needed. Wound debridement performed, offloading boot prescribed, Podiatry consult placed.',
      medications: 'Metformin 1000mg BID, Glipizide 10mg daily, Gabapentin 300mg TID.',
    },
    createdAt: '2026-02-05T11:00:00Z',
    updatedAt: '2026-02-08T09:45:00Z',
    closedAt: null,
  },
  {
    id: 'case-003',
    patientId: 'pat-007',
    caseNumber: 'CASE-2026-0003',
    title: 'Transient Ischemic Attack (TIA) with Left Facial Droop & Dysphasia',
    consultationReason: 'Sudden left-sided weakness and difficulty speaking lasting 25 minutes before full resolution.',
    status: 'New',
    priority: 'Urgent',
    department: 'Neurology',
    responsibleUserId: 'usr-marcus-thorne',
    clinicalDocumentation: {
      chiefComplaint: 'Brief episode of slurred speech and left arm clumsiness at breakfast.',
      historyOfPresentIllness: 'Spouse noticed patient dropping his fork and slurring words at 08:00 AM. Fully returned to baseline neurological exam by 08:30 AM.',
      medicalHistory: 'Non-valvular Atrial Fibrillation, Hypertension, Previous smoker (quit 2010).',
      familySocialHistory: 'Brother died of ischemic stroke at age 75.',
      examinationFindings: 'NIHSS = 0 upon presentation. Alert and fully oriented x4. Cranial nerves II-XII intact. Motor strength 5/5 in all four extremities. Reflexes symmetric.',
      investigations: 'Non-contrast CT Head: No acute intracranial hemorrhage or territorial infarction. MRI Brain with DWI: Small punctate diffusion restriction in right MCA territory. Carotid Doppler: 60% right ICA stenosis.',
      assessmentAndPlan: 'Acute TIA / minor ischemic stroke in setting of suboptimal anticoagulation. Initiated Apixaban 5mg BID. Statin therapy maximized. Vascular surgery consult for carotid stenosis review.',
      medications: 'Apixaban 5mg BID, Rosuvastatin 40mg daily, Lisinopril 20mg daily.',
    },
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-10T12:00:00Z',
    closedAt: null,
  },
  {
    id: 'case-004',
    patientId: 'pat-005',
    caseNumber: 'CASE-2026-0004',
    title: 'Acute Kidney Injury Superimposed on Stage 3b Chronic Kidney Disease',
    consultationReason: 'Elevated serum creatinine detected on routine outpatient surveillance, lethargy and mild peripheral edema.',
    status: 'Under Review',
    priority: 'High',
    department: 'General Medicine',
    responsibleUserId: 'usr-sarah-chen',
    clinicalDocumentation: {
      chiefComplaint: 'Weakness, decreased appetite, and dark urine over past 4 days.',
      historyOfPresentIllness: 'Patient recently took over-the-counter NSAIDs for severe knee osteoarthritis pain. Baseline creatinine 1.8 mg/dL jumped to 3.2 mg/dL.',
      medicalHistory: 'CKD Stage 3b (baseline eGFR 38), Benign Prostatic Hyperplasia, Hypertension.',
      familySocialHistory: 'Lives with spouse. No tobacco or alcohol.',
      examinationFindings: 'BP 154/88 mmHg, HR 74 bpm. Mild 1+ bilateral pitting pretibial edema. Jugular venous pressure flat. No asterixis.',
      investigations: 'Serum Creatinine: 3.2 mg/dL, BUN: 44 mg/dL, Serum Potassium: 5.2 mEq/L. Renal ultrasound: Bilateral increased cortical echogenicity, no hydronephrosis.',
      assessmentAndPlan: 'Prerenal AKI secondary to NSAID-induced renal vasoconstriction and dehydration. Discontinued all NSAIDs immediately. IV Isotonic Saline volume repletion at 75 mL/hr. Repeat electrolytes in 24 hours.',
      medications: 'Hold Lisinopril. Sodium polystyrene if K > 5.5 mEq/L. Tylenol for pain control.',
    },
    createdAt: '2026-02-12T14:00:00Z',
    updatedAt: '2026-02-13T10:30:00Z',
    closedAt: null,
  },
  {
    id: 'case-005',
    patientId: 'pat-004',
    caseNumber: 'CASE-2026-0005',
    title: 'Intractable Migraine with Visual Aura and Photophobia',
    consultationReason: 'Throbbing hemicranial headache persisting for 48 hours refractory to oral analgesics.',
    status: 'Active',
    priority: 'Normal',
    department: 'Neurology',
    responsibleUserId: 'usr-marcus-thorne',
    clinicalDocumentation: {
      chiefComplaint: 'Right temporal throbbing pain, severity 8/10, severe nausea and intolerance to light.',
      historyOfPresentIllness: 'Aaliyah experienced typical scintillating scotoma 1 hour before headache onset. Tried Sumatriptan 50mg with minimal relief.',
      medicalHistory: 'Episodic migraine without aura transitioning to chronic migraine pattern.',
      familySocialHistory: 'Mother has migraine disorder. Graduate student in engineering.',
      examinationFindings: 'Afebrile, BP 122/78 mmHg. Normal fundoscopic exam (no papilledema). Supple neck, negative Brudzinski/Kernig signs. Cranial nerves normal.',
      investigations: 'Brain MRI (previous year): Normal. Basic metabolic panel within normal limits.',
      assessmentAndPlan: 'Status migrainosus. Administered IV hydration, Ketorolac 30mg, Metoclopramide 10mg, and Dexamethasone 4mg. Initiated CGRP receptor antagonist preventive therapy.',
      medications: 'Rimegepant 75mg PRN, Propranolol 40mg daily.',
    },
    createdAt: '2026-02-14T08:30:00Z',
    updatedAt: '2026-02-14T16:00:00Z',
    closedAt: null,
  },
  {
    id: 'case-006',
    patientId: 'pat-006',
    caseNumber: 'CASE-2026-0006',
    title: 'Post-Operative Recovery following Laparoscopic Appendectomy',
    consultationReason: 'Routine post-surgical wound check and gastrointestinal tolerance evaluation.',
    status: 'Follow-up Required',
    priority: 'Normal',
    department: 'General Surgery',
    responsibleUserId: 'usr-sarah-chen',
    clinicalDocumentation: {
      chiefComplaint: 'Mild peri-umbilical incision tenderness, tolerating regular diet, flatus passed.',
      historyOfPresentIllness: 'Underwent uncomplicated laparoscopic appendectomy 4 days ago for acute suppurative appendicitis.',
      medicalHistory: 'No prior surgeries or significant medical conditions.',
      familySocialHistory: 'Non-smoker, college student.',
      examinationFindings: 'Abdomen soft, non-distended. Three laparoscopic ports clean and dry, minimal bruising, no erythema or purulent drainage.',
      investigations: 'Post-op CBC: WBC normalized from 14.5 to 7.8 x 10^9/L.',
      assessmentAndPlan: 'Post-operative day 4 status post laparoscopic appendectomy. Healing well, bowel function restored. Advised to avoid heavy lifting for 2 weeks.',
      medications: 'Acetaminophen 650mg Q6H PRN pain.',
    },
    createdAt: '2026-02-15T11:20:00Z',
    updatedAt: '2026-02-16T13:40:00Z',
    closedAt: null,
  },
  {
    id: 'case-007',
    patientId: 'pat-002',
    caseNumber: 'CASE-2026-0007',
    title: 'Moderate-Severe Asthma Exacerbation with Bronchospasm',
    consultationReason: 'Wheezing, nocturnal coughing fits, and reduced peak expiratory flow.',
    status: 'Resolved',
    priority: 'Normal',
    department: 'Pulmonology',
    responsibleUserId: 'usr-sarah-chen',
    clinicalDocumentation: {
      chiefComplaint: 'Chest tightness and shortness of breath following viral upper respiratory infection.',
      historyOfPresentIllness: 'Symptoms worsened over 5 days. Peak flow dropped from baseline 450 L/min to 280 L/min.',
      medicalHistory: 'Atopic Asthma since childhood, Allergic rhinitis.',
      familySocialHistory: 'Pet cat at home.',
      examinationFindings: 'SpO2 96% on room air. Expiratory wheezing throughout both lung fields. No accessory muscle use.',
      investigations: 'Peak Expiratory Flow: 280 L/min (62% predicted). Chest X-ray: Hyperinflation without focal infiltrates.',
      assessmentAndPlan: 'Viral-induced asthma exacerbation. Completed 5-day course of oral Prednisone 40mg. Inhaled Budesonide/Formoterol maintenance stepped up. Peak flow back to 440 L/min.',
      medications: 'Budesonide/Formoterol 160/4.5 mcg 2 puffs BID, Albuterol HFA PRN.',
    },
    createdAt: '2026-01-28T10:00:00Z',
    updatedAt: '2026-02-04T15:30:00Z',
    closedAt: '2026-02-04T15:30:00Z',
  },
  {
    id: 'case-008',
    patientId: 'pat-008',
    caseNumber: 'CASE-2026-0008',
    title: 'Subacute Thyroiditis Management & Levothyroxine Titration',
    consultationReason: 'Anterior neck tenderness and persistent fatigue following viral pharyngitis.',
    status: 'Closed',
    priority: 'Low',
    department: 'Endocrinology',
    responsibleUserId: 'usr-marcus-thorne',
    clinicalDocumentation: {
      chiefComplaint: 'Neck discomfort radiating to jaw, palpitations now transitioned to sluggishness.',
      historyOfPresentIllness: 'Biphasic course with early hyperthyroidism followed by transient hypothyroid phase.',
      medicalHistory: 'Mild osteopenia.',
      familySocialHistory: 'Maternal aunt with Hashimoto thyroiditis.',
      examinationFindings: 'Thyroid mildly enlarged and tender on palpation. Heart rate 68 bpm. Reflex relaxation phase normal.',
      investigations: 'Free T4: 1.1 ng/dL (normalized), TSH: 2.4 mIU/L (normalized), ESR: 18 mm/hr (down from 62).',
      assessmentAndPlan: 'Resolved subacute granulomatous thyroiditis. Euthyroid state achieved. Symptoms completely resolved. Case closed.',
      medications: 'None currently needed.',
    },
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-02-02T11:00:00Z',
    closedAt: '2026-02-02T11:00:00Z',
  },
];

export const INITIAL_FOLLOWUPS: CaseFollowup[] = [
  {
    id: 'flw-001',
    caseId: 'case-001',
    caseNumber: 'CASE-2026-0001',
    caseTitle: 'Acute Coronary Syndrome / Post-PCI Stent Surveillance',
    patientId: 'pat-001',
    patientName: 'Arthur Pendelton',
    assignedTo: 'usr-sarah-chen',
    assignedToName: 'Dr. Sarah Chen, MD',
    followupDate: '2026-02-05', // OVERDUE in relation to mid-Feb
    purpose: 'Post-stent 48h telemetry review, access site hematoma check, and high-dose Statin tolerance.',
    status: 'Pending',
    outcome: null,
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-02-01T11:00:00Z',
  },
  {
    id: 'flw-002',
    caseId: 'case-002',
    caseNumber: 'CASE-2026-0002',
    caseTitle: 'Uncontrolled Type 2 Diabetes with Neuropathic Plantar Ulcer',
    patientId: 'pat-003',
    patientName: 'Carlos Morales',
    assignedTo: 'usr-james-rodriguez',
    assignedToName: 'James Rodriguez, RN',
    followupDate: '2026-02-12', // OVERDUE
    purpose: 'Diabetic foot ulcer wound dressing change, measurement of wound depth, and offloading compliance check.',
    status: 'Pending',
    outcome: null,
    createdAt: '2026-02-05T12:00:00Z',
    updatedAt: '2026-02-05T12:00:00Z',
  },
  {
    id: 'flw-003',
    caseId: 'case-004',
    caseNumber: 'CASE-2026-0004',
    caseTitle: 'Acute Kidney Injury Superimposed on Stage 3b CKD',
    patientId: 'pat-005',
    patientName: 'Robert MacIntyre',
    assignedTo: 'usr-sarah-chen',
    assignedToName: 'Dr. Sarah Chen, MD',
    followupDate: new Date().toISOString().split('T')[0], // TODAY
    purpose: 'Repeat basic metabolic panel: serum creatinine, BUN, and potassium after 48 hours of IV hydration.',
    status: 'Scheduled',
    outcome: null,
    createdAt: '2026-02-12T15:00:00Z',
    updatedAt: '2026-02-12T15:00:00Z',
  },
  {
    id: 'flw-004',
    caseId: 'case-006',
    caseNumber: 'CASE-2026-0006',
    caseTitle: 'Post-Operative Recovery following Laparoscopic Appendectomy',
    patientId: 'pat-006',
    patientName: 'Maya Patel',
    assignedTo: 'usr-james-rodriguez',
    assignedToName: 'James Rodriguez, RN',
    followupDate: '2026-02-28', // UPCOMING
    purpose: 'Surgical staple / subcuticular suture inspection, activity tolerance review, and discharge clearance.',
    status: 'Scheduled',
    outcome: null,
    createdAt: '2026-02-15T12:00:00Z',
    updatedAt: '2026-02-15T12:00:00Z',
  },
  {
    id: 'flw-005',
    caseId: 'case-007',
    caseNumber: 'CASE-2026-0007',
    caseTitle: 'Moderate-Severe Asthma Exacerbation with Bronchospasm',
    patientId: 'pat-002',
    patientName: 'Eleanor Vance',
    assignedTo: 'usr-sarah-chen',
    assignedToName: 'Dr. Sarah Chen, MD',
    followupDate: '2026-02-04',
    purpose: 'Evaluate post-steroid burst peak expiratory flow and step-down inhaler regimen.',
    status: 'Completed',
    outcome: 'Peak flow fully normalized to 450 L/min. Patient reports zero nocturnal awakening or cough.',
    createdAt: '2026-01-28T11:00:00Z',
    updatedAt: '2026-02-04T15:30:00Z',
    completedAt: '2026-02-04T15:30:00Z',
  },
];

export const INITIAL_NOTES: CaseNote[] = [
  {
    id: 'note-001',
    caseId: 'case-001',
    authorId: 'usr-sarah-chen',
    authorName: 'Dr. Sarah Chen, MD',
    authorRole: 'Doctor',
    noteType: 'Clinical Note',
    content: 'Coronary angiogram revealed 95% thrombotic occlusion of mid-RCA. Successful thrombectomy and deployment of a 3.5 x 24mm Synergy drug-eluting stent. TIMI 3 flow achieved with zero residual stenosis.',
    isAmendment: false,
    createdAt: '2026-02-01T12:30:00Z',
    updatedAt: '2026-02-01T12:30:00Z',
  },
  {
    id: 'note-002',
    caseId: 'case-001',
    authorId: 'usr-james-rodriguez',
    authorName: 'James Rodriguez, RN',
    authorRole: 'Nurse',
    noteType: 'Observation / Nursing',
    content: 'Right femoral artery puncture site assessed. Pressure dressing intact, no thrill or bruit, pedal pulses 2+ strong bilaterally. Patient resting quietly with pain scale 0/10.',
    isAmendment: false,
    createdAt: '2026-02-01T16:00:00Z',
    updatedAt: '2026-02-01T16:00:00Z',
  },
  {
    id: 'note-003',
    caseId: 'case-002',
    authorId: 'usr-sarah-chen',
    authorName: 'Dr. Sarah Chen, MD',
    authorRole: 'Doctor',
    noteType: 'Clinical Note',
    content: 'Sharp debridement of non-viable hyperkeratotic tissue completed under sterile technique. Wound measured at 1.4 cm length x 1.1 cm width x 0.2 cm depth. Clean bleeding base stimulated.',
    isAmendment: false,
    createdAt: '2026-02-05T11:45:00Z',
    updatedAt: '2026-02-05T11:45:00Z',
  },
  {
    id: 'note-004',
    caseId: 'case-002',
    authorId: 'usr-james-rodriguez',
    authorName: 'James Rodriguez, RN',
    authorRole: 'Nurse',
    noteType: 'Care Plan',
    content: 'Hydrogel dressing applied with non-adherent sterile foam pad. Fitted with specialized offloading diabetic boot. Patient demonstrated correct boot application technique.',
    isAmendment: false,
    createdAt: '2026-02-05T12:30:00Z',
    updatedAt: '2026-02-05T12:30:00Z',
  },
  {
    id: 'note-005',
    caseId: 'case-003',
    authorId: 'usr-marcus-thorne',
    authorName: 'Dr. Marcus Thorne, MD',
    authorRole: 'Doctor',
    noteType: 'Consultation',
    content: 'Urgent stroke neurology consult: Presentation is classic for left hemispheric transient ischemic attack. In view of carotid stenosis, urgent vascular referral submitted for endarterectomy consideration.',
    isAmendment: false,
    createdAt: '2026-02-10T10:15:00Z',
    updatedAt: '2026-02-10T10:15:00Z',
  },
];

export const INITIAL_EVENTS: CaseEvent[] = [
  {
    id: 'evt-001',
    caseId: 'case-001',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorRole: 'Doctor',
    eventType: 'CASE_CREATED',
    description: 'Initial case opened for Acute Coronary Syndrome.',
    metadata: { initialPriority: 'Urgent', initialStatus: 'Active' },
    createdAt: '2026-02-01T10:30:00Z',
  },
  {
    id: 'evt-002',
    caseId: 'case-001',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorRole: 'Doctor',
    eventType: 'NOTE_ADDED',
    description: 'Clinical documentation and angiogram operative summary added.',
    metadata: { noteType: 'Clinical Note' },
    createdAt: '2026-02-01T12:30:00Z',
  },
  {
    id: 'evt-003',
    caseId: 'case-001',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorRole: 'Doctor',
    eventType: 'FOLLOWUP_SCHEDULED',
    description: 'Scheduled follow-up for post-stent 48h telemetry review.',
    metadata: { followupDate: '2026-02-05', assignedTo: 'usr-sarah-chen' },
    createdAt: '2026-02-01T13:00:00Z',
  },
  {
    id: 'evt-004',
    caseId: 'case-002',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorRole: 'Doctor',
    eventType: 'CASE_CREATED',
    description: 'Case opened for Uncontrolled Type 2 Diabetes with Neuropathic Plantar Ulcer.',
    metadata: { priority: 'High', status: 'Active' },
    createdAt: '2026-02-05T11:00:00Z',
  },
  {
    id: 'evt-005',
    caseId: 'case-002',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorRole: 'Doctor',
    eventType: 'STATUS_CHANGED',
    description: 'Status changed from Active to Follow-up Required.',
    metadata: { previousStatus: 'Active', newStatus: 'Follow-up Required' },
    createdAt: '2026-02-08T09:45:00Z',
  },
  {
    id: 'evt-006',
    caseId: 'case-003',
    actorId: 'usr-marcus-thorne',
    actorName: 'Dr. Marcus Thorne, MD',
    actorRole: 'Doctor',
    eventType: 'CASE_CREATED',
    description: 'Emergency Neurology case created for TIA evaluation.',
    metadata: { priority: 'Urgent', status: 'New' },
    createdAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'evt-007',
    caseId: 'case-007',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorRole: 'Doctor',
    eventType: 'FOLLOWUP_COMPLETED',
    description: 'Follow-up completed: Peak expiratory flow normalized.',
    metadata: { outcome: 'Peak flow fully normalized to 450 L/min.' },
    createdAt: '2026-02-04T15:30:00Z',
  },
  {
    id: 'evt-008',
    caseId: 'case-007',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorRole: 'Doctor',
    eventType: 'CASE_CLOSED',
    description: 'Case status transitioned to Resolved / Closed.',
    metadata: { finalStatus: 'Resolved' },
    createdAt: '2026-02-04T15:30:00Z',
  },
];

export const INITIAL_ATTACHMENTS: Attachment[] = [
  {
    id: 'att-001',
    caseId: 'case-001',
    uploadedBy: 'usr-sarah-chen',
    uploaderName: 'Dr. Sarah Chen, MD',
    storagePath: 'cases/case-001/attachments/ecg_12lead_stemi.pdf',
    originalFilename: '12_Lead_ECG_Inferior_STEMI.pdf',
    mimeType: 'application/pdf',
    fileSize: 1420500,
    createdAt: '2026-02-01T10:45:00Z',
  },
  {
    id: 'att-002',
    caseId: 'case-001',
    uploadedBy: 'usr-sarah-chen',
    uploaderName: 'Dr. Sarah Chen, MD',
    storagePath: 'cases/case-001/attachments/rca_angiogram_cine.png',
    originalFilename: 'Coronary_Angiogram_Pre_and_Post_DES.png',
    mimeType: 'image/png',
    fileSize: 3240800,
    createdAt: '2026-02-01T12:40:00Z',
  },
  {
    id: 'att-003',
    caseId: 'case-002',
    uploadedBy: 'usr-james-rodriguez',
    uploaderName: 'James Rodriguez, RN',
    storagePath: 'cases/case-002/attachments/foot_ulcer_measurement.png',
    originalFilename: 'Plantar_Ulcer_Wound_Grid_Baseline.png',
    mimeType: 'image/png',
    fileSize: 2150300,
    createdAt: '2026-02-05T12:15:00Z',
  },
  {
    id: 'att-004',
    caseId: 'case-003',
    uploadedBy: 'usr-marcus-thorne',
    uploaderName: 'Dr. Marcus Thorne, MD',
    storagePath: 'cases/case-003/attachments/mri_brain_dwi.pdf',
    originalFilename: 'Brain_MRI_DWI_Stroke_Protocol.pdf',
    mimeType: 'application/pdf',
    fileSize: 4501200,
    createdAt: '2026-02-10T11:30:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    userId: 'usr-sarah-chen',
    type: 'FOLLOWUP_OVERDUE',
    title: 'Overdue Follow-up: Arthur Pendelton',
    message: 'Post-stent 48h telemetry review was due on 2026-02-05.',
    relatedCaseId: 'case-001',
    readAt: null,
    createdAt: '2026-02-06T08:00:00Z',
  },
  {
    id: 'notif-002',
    userId: 'usr-james-rodriguez',
    type: 'FOLLOWUP_OVERDUE',
    title: 'Overdue Follow-up: Carlos Morales',
    message: 'Diabetic foot ulcer wound dressing change was due on 2026-02-12.',
    relatedCaseId: 'case-002',
    readAt: null,
    createdAt: '2026-02-13T08:00:00Z',
  },
  {
    id: 'notif-003',
    userId: 'usr-sarah-chen',
    type: 'FOLLOWUP_UPCOMING',
    title: 'Follow-up Scheduled Today: Robert MacIntyre',
    message: 'Repeat basic metabolic panel: creatinine, BUN, and potassium scheduled for today.',
    relatedCaseId: 'case-004',
    readAt: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-004',
    userId: 'usr-marcus-thorne',
    type: 'CASE_ASSIGNED',
    title: 'New Case Assigned: Harold Zimmer',
    message: 'Urgent TIA workup assigned to your care.',
    relatedCaseId: 'case-003',
    readAt: null,
    createdAt: '2026-02-10T09:05:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorEmail: 'dr.sarah@medora.health',
    actorRole: 'Doctor',
    action: 'CREATE_CASE',
    entityType: 'CASE',
    entityId: 'case-001',
    metadata: { caseNumber: 'CASE-2026-0001', priority: 'Urgent', patientId: 'pat-001' },
    createdAt: '2026-02-01T10:30:00Z',
  },
  {
    id: 'aud-002',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorEmail: 'dr.sarah@medora.health',
    actorRole: 'Doctor',
    action: 'ADD_CLINICAL_NOTE',
    entityType: 'NOTE',
    entityId: 'note-001',
    metadata: { caseId: 'case-001', noteType: 'Clinical Note' },
    createdAt: '2026-02-01T12:30:00Z',
  },
  {
    id: 'aud-003',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorEmail: 'dr.sarah@medora.health',
    actorRole: 'Doctor',
    action: 'CREATE_FOLLOWUP',
    entityType: 'FOLLOWUP',
    entityId: 'flw-001',
    metadata: { caseId: 'case-001', dueDate: '2026-02-05' },
    createdAt: '2026-02-01T13:00:00Z',
  },
  {
    id: 'aud-004',
    actorId: 'usr-sarah-chen',
    actorName: 'Dr. Sarah Chen, MD',
    actorEmail: 'dr.sarah@medora.health',
    actorRole: 'Doctor',
    action: 'UPDATE_CASE_STATUS',
    entityType: 'CASE',
    entityId: 'case-002',
    metadata: { from: 'Active', to: 'Follow-up Required' },
    createdAt: '2026-02-08T09:45:00Z',
  },
  {
    id: 'aud-005',
    actorId: 'usr-marcus-thorne',
    actorName: 'Dr. Marcus Thorne, MD',
    actorEmail: 'dr.marcus@medora.health',
    actorRole: 'Doctor',
    action: 'CREATE_CASE',
    entityType: 'CASE',
    entityId: 'case-003',
    metadata: { caseNumber: 'CASE-2026-0003', priority: 'Urgent', patientId: 'pat-007' },
    createdAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'aud-006',
    actorId: 'usr-elena-rostova',
    actorName: 'Elena Rostova',
    actorEmail: 'admin.elena@medora.health',
    actorRole: 'Administrator',
    action: 'USER_LOGIN',
    entityType: 'AUTH',
    entityId: 'usr-elena-rostova',
    metadata: { ip: '127.0.0.1', userAgent: 'Medora Clinical Client v1.0' },
    createdAt: '2026-02-15T08:00:00Z',
  },
];
